### ISSUE TITLE
How i can skip auth?

### ISSUE THREAD

**Issue by vmpartner** [domodwyer/mailyak#29] opened 2018-09-10 20:40 UTC
My server doesnt support auth and i get error "server doesn't support AUTH". Can i skip auth?

**Comment by domodwyer** [comment] 2018-09-12 20:53
Hi @vmpartner 

Have you tried passing `nil` as the auth? As in, `mailyak.New("smtp.itsallbroken.com:25", nil)`?

Dom

**Comment by vmpartner** [comment] 2018-09-13 07:17
Hi @domodwyer, thank you for response. Yes, but therere need instanse of smtp.Auth ```func New(host string, auth smtp.Auth) *MailYak```

**Comment by vmpartner** [comment] 2018-09-13 07:18
I tried send empty filled auth, but get error from server, that server doesn't support AUTH

**Comment by domodwyer** [comment] 2018-09-16 11:08
Hi @vmpartner 

Mailyak uses the [golang smtp package](https://golang.org/pkg/net/smtp/) and it looks like [passing nil](https://sourcegraph.com/github.com/golang/go@go1.10/-/blob/src/net/smtp/smtp.go#L345) disables sending AUTH to the server.

I can't really help without knowing what SMTP server you're using, or seeing your code but it looks like mailyak should work as intended here so I'll go ahead and close this.

Dom

**Closed by domodwyer** 2018-09-16 11:08 UTC
Labels: question
